require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'romegamart' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'smartlook-react-native-bridge', :path => '../node_modules/smartlook-react-native-wrapper'

  target 'romegamartTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end